services:

  webserver:
    image: nodeserver:1
    build: .
    # ports:
    #   - 8080:8080
    develop:
      watch:
        - action: sync+restart # 복붙 + 재시작
          path: . # 어떤 파일을
          target: /app # 어디에
          ignore:
            - node_modules/ # 제외 (dockerignore가 있으면 필요 X)
        - action: rebuild # path 파일들 변경시 자동으로 docker build
          path: package.json

    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - mynet1
      - mynet2

  nginx:
    image: nginx:1
    ports:
      - 80:80
    networks:
      - mynet1
    restart: always

  db:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    # env_file:
    #   - fileName.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - test_vol:/var/lib/postgresql/data
      # - HOST_PATH:/var/lib/postgresql/data # bind mount (내가 원하는 경로랑 싱크)
    networks:
      - mynet2

networks:
  mynet1:
  mynet2:


volumes:
  test_vol:
    external: true # 만들어둔 볼륨 사용하려면 필요. 만약 이 항목이 없으면 docker_test_val 로 생성됨.
